name: snowflake_client
description: Snowflake client project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.1.0
  flutter_screenutil: ^5.5.4
  flutter_svg: ^2.0.2
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dictionary/
    - assets/image/
    - assets/image/background/

  fonts:
    - family: AnastasiaScript
      fonts:
        - asset: assets/font/AnastasiaScript.ttf
