const raceOptions = {'human': 1, 'elf': 2};

const sexOptions = {'male': 1, 'female': 2};

const hairOptions = {
  'color': [
    'white hair',
    'brown hair',
    'red hair',
    'pink hair',
    'orange hair',
    'yellow hair',
    'Blonde hair',
    'light green hair',
    'green hair',
    'sky blue hair',
    'blue hair',
    'purple hair',
    'black hair',
  ],
  'shape': [
    'short_hair',
    'very_short_hair',
    'absurdly_short_hair',
    'medium_hair',
    'long_hair',
    'very_long_hair',
    'absurdly_long_hair',
    'straight_hair',
    'curly_hair',
    'wavy_hair',
    'spiked_hair',
    'flipped_hair',
    'bluntbangs',
    'pointy_hair',
    'messy_hair',
    'Blunt_bangs',
    'parted_bangs',
    'crossed_bangs',
    'swept_bangs',
    'braided_bangs',
    'hair_over_one_eye',
    'hair_over_eyes',
    'hair_between_eyes',
    'asymmetrical_bangs',
  ],
  'style': [
    'pixie_cut',
    'undercut',
    'cornrows',
    'dreadlocks',
    'braid',
    'braided_bangs',
    'front_braid',
    'side_braid',
    'french_braid',
    'crown_braid',
    'single_braid',
    'multiple_braids',
    'twin_braids',
    'tri_braids',
    'quad_braids',
    'hair_bun',
    'braided_bun',
    'single_hair_bun',
    'double_bun',
    'triple_bun',
    'cone_hair_bun',
    'doughnut_hair_bun',
    'heart_hair_bun',
    'one_side_up',
    'two_side_up',
    'ponytail',
    'folded_ponytail',
    'front_ponytail',
    'high_ponytail',
    'short_ponytail',
    'side_ponytail',
    'split_ponytail',
    'twintails',
    'low_twintails',
    'short_twintails',
    'uneven_twintails',
    'tri_tails',
    'quad_tails',
    'quin_tails',
  ],
};

const faceOptions = [
  'small_face',
  'small_medium_face',
  'medium_face',
  'large_face',
  'huge_face',
  'sharp_face',
  'pointed_face',
  'peanut_face',
  'round_face',
  'egg-shaped_face',
  'triangular_face',
  'inverted_triangle_of_faces',
  'squareface',
  'diamond_face',
  'hexagonal_face',
];

const eyesOptions = [
  'gray_eyes',
  'white_eyes',
  'brown_eyes',
  'red_eyes',
  'pink_eyes',
  'orange_eyes',
  'yellow_eyes',
  'golden_eyes',
  'light_green_eyes',
  'green_eyes',
  'sky_blue_eyes',
  'blue_eyes',
  'purple_eyes',
  'black_eyes',
];

const noseOptions = [
  'small_nose',
  'long_nose',
  'slender_nose',
  'heavy_nose',
  'broad_nose',
  'high-end_nose',
  'wild_boogged_nose',
  'aquiline_nose',
];

const mouthOptions = [
  'small_mouth',
  'big_mouth',
  'thin_lips',
  'thick_lips',
];

const bodyOptions = ['slender'];

const breastOptions = [
  'flat_chest',
  'small_breasts',
  'small_medium_breasts',
  'medium_breasts',
  'large_breasts',
  'huge_breasts',
  'gigantic_breasts',
];
