local:
  baseUrl: http://localhost:10000/v1
  s3:
    generatedAiImage: https://f002.backblazeb2.com/file/yukki-studio/snowflake/generated-ai-image/
  chat:
    host: localhost
    port: 10002
  map:
    host: localhost
    port: 10003
  service:
    host: localhost
    port: 10004

production:
  baseUrl: https://snowflake-login-api.yukki.app/v1
  s3:
    generatedAiImage: https://f002.backblazeb2.com/file/yukki-studio/snowflake/generated-ai-image/
  chat:
    host: snowflake-chat.yukki.app
    port: 10002
  map:
    host: snowflake-map.yukki.app
    port: 10003
  service:
    host: snowflake-service.yukki.app
    port: 10004
